package se.alexander.portfolio.chess;

import org.junit.jupiter.api.Test;
import org.springframework.boot.test.context.SpringBootTest;

@SpringBootTest
class ChessApplicationTests {

    @Test
    void contextLoads() {
        // pre-generated by Spring Boot Initilizr
    }
    
    @Test
    void firstTest() {

    }

}
